export const serverHostList = [
  {"clientEndpoint": "localhost", "serverEndpoint": "http://localhost:8104"},
  {"clientEndpoint": "sit.e-labs.ai", "serverEndpoint": "https://sitserverelabs.e-labs.ai"},
  {"clientEndpoint": "dev.e-labs.ai", "serverEndpoint": "https://devserverelabs.e-labs.ai"}, 
  {"clientEndpoint": "uat.e-labs.ai", "serverEndpoint": "https://uatserverelabs.e-labs.ai"},  
  {"clientCode": "SANS-SANS01-SIT", "clientEndpoint": "sit-sanskar.e-labs.ai", "serverEndpoint": "https://sitsanskarserver.e-labs.ai"},
  {"clientCode": "SANS-SANS01", "clientEndpoint": "lims-sanskar.e-labs.ai", "serverEndpoint": "https://prodsanskarserver.e-labs.ai"},  
  {"clientEndpoint": "hardgoodslabs.e-labs.ai", "serverEndpoint": "https://serverhardgoodlabs.e-labs.ai"},
  {"clientCode": "DEMO-DEMO01", "clientEndpoint": "demolab.e-labs.ai", "serverEndpoint": "https://serverhardgoodlabs.e-labs.ai"},
  {"clientEndpoint": "lite-demolab.e-labs.ai", "serverEndpoint": "https://serverhardgoodlabs.e-labs.ai"},
  {"clientEndpoint": "standard-demolab.e-labs.ai", "serverEndpoint": "https://serverhardgoodlabs.e-labs.ai"},
  {"clientCode": "ASC-ASC01-SIT", "clientEndpoint": "ascgroup.e-labs.ai", "serverEndpoint": "https://sitserverascgroup.e-labs.ai"},
  {"clientEndpoint": "uatclients.e-labs.ai", "serverEndpoint": "https://sitserverascgroup.e-labs.ai"},
  {"clientCode": "ASC-ASC01", "clientEndpoint": "erpsuite.ascgroup.co.in", "serverEndpoint": "https://prodserverascgroup.e-labs.ai"},
  {"clientEndpoint": "itclabs.e-labs.ai", "serverEndpoint": "https://serveritclabs.e-labs.ai"},
  {"clientEndpoint": "dev-itclabs.e-labs.ai", "serverEndpoint": "https://devserveritclabs.e-labs.ai"},
  {"clientCode": "ITC-ITC01-UAT", "clientEndpoint": "uat-itclabs.e-labs.ai", "serverEndpoint": "https://uatserveritclabs.e-labs.ai"},
  {"clientCode": "ITC-ITC01", "clientEndpoint": "lims.itclabs.com", "serverEndpoint": "https://prodserveritclabs.e-labs.ai"},
  {"clientEndpoint": "qualiteklab.e-labs.ai", "serverEndpoint": "https://serverqualiteklab.e-labs.ai"},
  {"clientEndpoint": "uat-qualiteklab.e-labs.ai", "serverEndpoint": "https://uatserverqualiteklab.e-labs.ai"},
  {"clientCode": "QUAL-QUALI01", "clientEndpoint": "lims.qualiteklab.com", "serverEndpoint": "https://prodserverqualiteklab.e-labs.ai"},
  {"clientEndpoint": "dev-qualiteklab.e-labs.ai", "serverEndpoint": "https://devserverqualiteklab.e-labs.ai"},
  {"clientEndpoint": "sit-hitech.e-labs.ai", "serverEndpoint": "https://sithitechserver.e-labs.ai"},
  {"clientEndpoint": "lims-hitech.e-labs.ai", "serverEndpoint": "https://prodhitechserver.e-labs.ai"},
  {"clientEndpoint": "sit-aalbiosciences.e-labs.ai", "serverEndpoint": "https://sitaalbiosciencesserver.e-labs.ai"},
  {"clientCode": "AABIO-AABIO01", "clientEndpoint": "lims-aalbiosciences.e-labs.ai", "serverEndpoint": "https://prodaalbiosciencesserver.e-labs.ai"},
  {"clientCode": "QUAL-QUALI02", "clientEndpoint": "bbsr-lims.qualiteklab.com", "serverEndpoint": "https://prodserverbbsrqualiteklab.e-labs.ai"},
  {"clientEndpoint": "bbsr-lims.e-labs.ai", "serverEndpoint": "https://prodserverbbsrqualiteklab.e-labs.ai"},
  {"clientEndpoint": "sit-multani.e-labs.ai", "serverEndpoint": "https://sitmultaniserver.e-labs.ai"},
  {"clientEndpoint": "app.multani.com", "serverEndpoint": "http://server.multani.com:30051"},
  {"clientEndpoint": "food.multani.com", "serverEndpoint": "http://server.multani.com:30051"},
  {"clientEndpoint": "lims-pharma-multani.e-labs.ai", "serverEndpoint": "https://prodmultaniserver.e-labs.ai"},
  {"clientEndpoint": "lims-food-multani.e-labs.ai", "serverEndpoint": "https://prodmultaniserver.e-labs.ai"},
  {"clientEndpoint": "lims-multani.e-labs.ai", "serverEndpoint": "https://sitmultaniserver.e-labs.ai"},  
  {"clientCode": "SAT-SAT01", "clientEndpoint": "web.sralabs.com", "serverEndpoint": "https://prodsatiateserver.e-labs.ai"},
  {"clientEndpoint": "app.e-labs.ai", "serverEndpoint": "https://serverelabs.e-labs.ai"},
  {"clientCode": "CENT-CENT01-SIT", "clientEndpoint": "sit-central.e-labs.ai", "serverEndpoint": "https://sitservercentrallims.e-labs.ai"},
  {"clientCode": "CENT-CENT01", "clientEndpoint": "central.e-labs.ai", "serverEndpoint": "https://prodservercentral.e-labs.ai"},
  {"clientCode": "UPMA-UPMA01", "clientEndpoint": "upma-lims.e-labs.ai", "serverEndpoint": "https://prodserverupma.e-labs.ai"},
  {"clientCode": "IIRT-IIRT01", "clientEndpoint": "erp.iirt.co.in", "serverEndpoint": "https://prodiirtserver.e-labs.ai"},
  {"clientCode": "COMP-COMPASS01", "clientEndpoint": "compassgroup.e-labs.ai", "serverEndpoint": "https://prodservercompassgroup.e-labs.ai"},
  {"clientCode": "TICS-TICS01", "clientEndpoint": "lims.theticslab.com", "serverEndpoint": "https://prodservertheticslab.e-labs.ai"}
]

