export const serverHostList = [
  {"clientEndpoint": "localhost", "serverEndpoint": "http://localhost:8104"},
  {"clientCode": "ELABS-ELABS01-SIT", "clientEndpoint": "sit.elabss.ai", "serverEndpoint": "https://sitserverelabs.elabss.ai"},
  {"clientCode": "ELABS-ELABS01-DEV", "clientEndpoint": "dev.elabss.ai", "serverEndpoint": "https://devserverelabs.elabss.ai"}, 
  {"clientCode": "ELABS-ELABS01-UAT", "clientEndpoint": "uat.elabss.ai", "serverEndpoint": "https://uatserverelabs.elabss.ai"},  
  {"clientCode": "SANS-SANS01-SIT", "clientEndpoint": "sit-sanskar.elabss.ai", "serverEndpoint": "https://sitsanskarserver.elabss.ai"},
  {"clientCode": "SANS-SANS01", "clientEndpoint": "lims-sanskar.elabss.ai", "serverEndpoint": "https://prodsanskarserver.elabss.ai"},  
  {"clientEndpoint": "hardgoodslabs.elabss.ai", "serverEndpoint": "https://serverhardgoodlabs.elabss.ai"},
  {"clientCode": "DEMO-DEMO01", "clientEndpoint": "demolab.elabss.ai", "serverEndpoint": "https://serverhardgoodlabs.elabss.ai"},
  {"clientEndpoint": "lite-demolab.elabss.ai", "serverEndpoint": "https://serverhardgoodlabs.elabss.ai"},
  {"clientEndpoint": "standard-demolab.elabss.ai", "serverEndpoint": "https://serverhardgoodlabs.elabss.ai"},
  {"clientCode": "ASC-ASC01-SIT", "clientEndpoint": "ascgroup.elabss.ai", "serverEndpoint": "https://sitserverascgroup.elabss.ai"},
  {"clientEndpoint": "uatclients.elabss.ai", "serverEndpoint": "https://sitserverascgroup.elabss.ai"},
  {"clientCode": "ASC-ASC01", "clientEndpoint": "erpsuite.ascgroup.co.in", "serverEndpoint": "https://prodserverascgroup.elabss.ai"},
  {"clientEndpoint": "itclabs.elabss.ai", "serverEndpoint": "https://serveritclabs.elabss.ai"},
  {"clientEndpoint": "dev-itclabs.elabss.ai", "serverEndpoint": "https://devserveritclabs.elabss.ai"},
  {"clientCode": "ITC-ITC01-UAT", "clientEndpoint": "uat-itclabs.elabss.ai", "serverEndpoint": "https://uatserveritclabs.elabss.ai"},
  {"clientEndpoint": "lims-itclabs.elabss.ai", "serverEndpoint": "https://prodserveritclabs.elabss.ai"},
  {"clientCode": "ITC-ITC01", "clientEndpoint": "lims.itclabs.com", "serverEndpoint": "https://prodserveritclabs.elabss.ai"},
  {"clientEndpoint": "qualiteklab.elabss.ai", "serverEndpoint": "https://serverqualiteklab.elabss.ai"},
  {"clientEndpoint": "uat-qualiteklab.elabss.ai", "serverEndpoint": "https://uatserverqualiteklab.elabss.ai"},
  {"clientCode": "QUAL-QUALI01", "clientEndpoint": "lims.qualiteklab.com", "serverEndpoint": "https://prodserverqualiteklab.elabss.ai"},
  {"clientEndpoint": "dev-qualiteklab.elabss.ai", "serverEndpoint": "https://devserverqualiteklab.elabss.ai"},
  {"clientEndpoint": "sit-hitech.elabss.ai", "serverEndpoint": "https://sithitechserver.elabss.ai"},
  {"clientEndpoint": "lims-hitech.elabss.ai", "serverEndpoint": "https://prodhitechserver.elabss.ai"},
  {"clientEndpoint": "sit-aalbiosciences.elabss.ai", "serverEndpoint": "https://sitaalbiosciencesserver.elabss.ai"},
  {"clientCode": "AABIO-AABIO01", "clientEndpoint": "lims-aalbiosciences.elabss.ai", "serverEndpoint": "https://prodaalbiosciencesserver.elabss.ai"},
  {"clientCode": "QUAL-QUALI02", "clientEndpoint": "bbsr-lims.qualiteklab.com", "serverEndpoint": "https://prodserverbbsrqualiteklab.elabss.ai"},
  {"clientEndpoint": "bbsr-lims.elabss.ai", "serverEndpoint": "https://prodserverbbsrqualiteklab.elabss.ai"},
  {"clientEndpoint": "sit-multani.elabss.ai", "serverEndpoint": "https://sitmultaniserver.elabss.ai"},
  {"clientEndpoint": "app.multani.com", "serverEndpoint": "http://server.multani.com:30051"},
  {"clientEndpoint": "food.multani.com", "serverEndpoint": "http://server.multani.com:30051"},
  {"clientEndpoint": "lims-pharma-multani.elabss.ai", "serverEndpoint": "https://prodmultaniserver.elabss.ai"},
  {"clientEndpoint": "lims-food-multani.elabss.ai", "serverEndpoint": "https://prodmultaniserver.elabss.ai"},
  {"clientEndpoint": "lims-multani.elabss.ai", "serverEndpoint": "https://sitmultaniserver.elabss.ai"},  
  {"clientCode": "SAT-SAT01", "clientEndpoint": "web.sralabs.com", "serverEndpoint": "https://prodsatiateserver.elabss.ai"},
  {"clientEndpoint": "app.elabss.ai", "serverEndpoint": "https://serverelabs.elabss.ai"},
  {"clientCode": "CENT-CENT01-SIT", "clientEndpoint": "sit-central.elabss.ai", "serverEndpoint": "https://sitservercentrallims.elabss.ai"},
  {"clientCode": "CENT-CENT01", "clientEndpoint": "central.elabss.ai", "serverEndpoint": "https://prodservercentral.elabss.ai"},
  {"clientCode": "UPMA-UPMA01", "clientEndpoint": "upma-lims.elabss.ai", "serverEndpoint": "https://prodserverupma.elabss.ai"},
  {"clientCode": "IIRT-IIRT01", "clientEndpoint": "erp.iirt.co.in", "serverEndpoint": "https://prodiirtserver.elabss.ai"},
  {"clientCode": "COMP-COMPASS01", "clientEndpoint": "compassgroup.elabss.ai", "serverEndpoint": "https://prodservercompassgroup.elabss.ai"},
  {"clientCode": "TICS-TICS01", "clientEndpoint": "lims.theticslab.com", "serverEndpoint": "https://prodservertheticslab.elabss.ai"},
  {"clientCode": "ITC-ITC01-DEV2", "clientEndpoint": "dev2.elabss.ai", "serverEndpoint": "https://dev2serverelabs.elabss.ai"},
  {"clientCode": "ITC-ITC01-SIT2", "clientEndpoint": "sit2.elabss.ai", "serverEndpoint": "https://sit2serverelabs.elabss.ai"},
  {"clientCode": "ITC-ITC01-UAT2", "clientEndpoint": "uat2.elabss.ai", "serverEndpoint": "https://uat2serverelabs.elabss.ai"}
]

