name: Docker Build - DEVELOP
on:
  push:
    branches: [ release/v** ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    ########################### Elabs Aws - ###########################
    # Elabs Aws
    - name: Configure AWS credentials Elabs
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.ELABS_AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.ELABS_AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.ELABS_REGION }}

    - name: Set Git Env
      run: echo $GITHUB_ENV
      
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
 
    - name: List of the GitHub Actions environment variables on Ubunt
      run: env  

    - name: Set up Node
      uses: actions/setup-node@v2
      with:
        node-version: '16'
    
    # - name: Installing source NPM dependencies...
    #   run: npm install
      
    # - name: Installing Angular
    #   run: npm install -g @angular/cli@15.2.10

    - name: Installing NPM and Angular
      run: |         
        CODEARTIFACT_AUTH_TOKEN=`aws codeartifact get-authorization-token --domain ui-libs --domain-owner 292474393014 --region ap-south-1 --query authorizationToken --output text`
        aws codeartifact login --tool npm --repository ui-library --domain ui-libs --domain-owner 292474393014 --region ap-south-1
        echo $CODEARTIFACT_AUTH_TOKEN        
        npm install -g @angular/cli@15.2.10
        npm install
    
    - name: Set Node Options
      run: echo "NODE_OPTIONS=--max_old_space_size=${{ secrets.RAM }}" >> $GITHUB_ENV

    - name: Get VERSION
      run: echo "VERSION=$GITHUB_RUN_NUMBER" >> $GITHUB_ENV
    
    - name: Find and Replace Version
      #uses: jacobtomlinson/gha-find-replace@v3
      #with:
      #  find: "[##VERSION##]"
      #  replace: "$(date +%Y%m%d)"
      #  include: "**package.json"
      run: |
        find . -name "**package.json" -exec sed -i "s/##VERSION##/$VERSION/g" {} +

    - name: Build, tag, and push image to Amazon ECR
      #  IMAGE_TAG: $VERSION-$GITHUB_RUN_NUMBER-$Availability -> not working
      run: |
        aws codeartifact login --tool npm --repository ui-library --domain ui-libs --domain-owner 292474393014 --region ap-south-1
        npm run my-lib-build
        ng build
        npm run my-lib-publish
        #cd service-lib
        #docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$VERSION-$GITHUB_RUN_NUMBER-$Availability .
        #docker push $ECR_REGISTRY/$ECR_REPOSITORY:$VERSION-$GITHUB_RUN_NUMBER-$Availability
